### ISSUE TITLE
The book is not free

### ISSUE THREAD

**Issue by Paratron** [mjavascript/mastering-modular-javascript#10]
Hosting the book on pony foo brings a problem with it: they lock the content until you register an twitter account and grant their app access to it so it can make advertising tweets on your behaviour.

If you dont want this or dont want a twitter account at all, the content remains locked for you. So technically the statement that the HTML version is free is not true.

Why do you host on pony foo in the first place? Github pages are really free and publishing is just a git commit to the correct branch...

**Comment by bevacqua** [comment]
You can read it here https://github.com/mjavascript/mastering-modular-javascript/blob/master/chapters/ch01.asciidoc
