### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by columnistdc** [mjavascript/mastering-modular-javascript#15]
Hi, may I add PR`s with russian translations(about 1 chapter in a week/two)?

**Comment by columnistdc** [comment]
Found an issue https://github.com/mjavascript/mastering-modular-javascript/issues/1. Close this^ please... Sorry

**Comment by bevacqua** [comment]
You may add it. If you intend to commercialize it then we'd have to talk with O'Reilly for that part
